### ISSUE TITLE
Types for plugin and support packages are exported incorrectly from respective package.json

### ISSUE THREAD

**Issue by Eric162** [currents-dev/cypress-debugger#55]
### Before opening, please confirm:

- [X] I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-debugger/issues) and [discussions](https://github.com/currents-dev/cypress-debugger/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 13.5
    CPU: (12) arm64 Apple M2 Max
    Memory: 242.45 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 3.5.0 - ~/universe3/universe/node_modules/.bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Safari: 16.6
  npmPackages:
    yup: 0.29.1 => 0.29.1
  npmGlobalPackages:
    corepack: 0.14.1
    npm: 8.19.2
    yarn: 1.22.18

```

</details>

### Describe the bug

When importing types from @currents/cypress-debugger-support and/or @currents/cypress-debugger-plugin, the types do not appear available.

This is happening because in each package's package.json. the `"types": "./src/index.ts"` should be instead `"types": "./dist/index.d.ts"`.

I will make a PR to address, but wanted to have the issue for tracking purposes.

### Expected behavior

The types should be available from these packages after installing.

### Command and Setup

<details>

### Command (share the exact `cypress` or `cypress-cloud` command you're running)        

```
# Put output below this line

N/A just for types

```

### Setup files cypress.config.j|ts|json

```
# Put output below this line

N/A just for types

```
</details>

### Full log and debug output

<details>

```
# Put your logs below this line

N/A just for types

```

</details>

**Comment by agoldis** [comment]
Fixed in 1.0.9
