### ISSUE TITLE
[CSR-811] network response cant able to view it showing always as [content] 

### ISSUE THREAD

**Issue by Arunk28** [currents-dev/cypress-debugger#58]
### Description

We tried to explore cypress debugger., all videos and network information are quite good 
but the response of the network request we cant able to track. 
it is always printing [content]

in all requests

### Example usage

please test with any network call tests

**Comment by agoldis** [comment]
@vCaisim would appreciate your help here

**Comment by Arunk28** [comment]
@agoldis  @vCaisim  any update on this issue ?  we need to see the response body so that it will be very useful
