### ISSUE TITLE
Cypress is blocking cypress-debugger

### ISSUE THREAD

**Issue by CaiqueCoelho** [currents-dev/cypress-debugger#65]
### Before opening, please confirm:

- [X] I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-debugger/issues) and [discussions](https://github.com/currents-dev/cypress-debugger/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

Cypress 13.2.0
Cypress-debugger 1.0.9

### Describe the bug

We've detected that you're using a 3rd party library that is not supported by Cypress: cypress-debugger

To continue running Cypress, please remove this library or reach out for help migrating.

https://on.cypress.io/unsupported-third-party-library?p=w53Ds8Oqw6zDn8Otw63Cp8Oew5%2FDnMOvw6HDocOfw6zCusKrwqjCqsKowrM%3D

### Expected behavior

Run Cypress with cypress-debugger

### Command and Setup

`npx cypress run --browser chrome --env grepTags=@smoke`

### Full log and debug output

> e2e:tests:smoke
> npx cypress run --browser chrome --env grepTags=@smoke

It looks like this is your first time using Cypress: 13.2.0

[STARTED] Task without title.
[SUCCESS] Task without title.

Opening Cypress...

DevTools listening on ws://127.0.0.1:35713/devtools/browser/449c2cb7-50f5-44a9-9857-9894fb947eab

We've detected that you're using a 3rd party library that is not supported by Cypress: cypress-debugger

To continue running Cypress, please remove this library or reach out for help migrating.

https://on.cypress.io/unsupported-third-party-library?p=w53Ds8Oqw6zDn8Otw63Cp8Oew5%2FDnMOvw6HDocOfw6zCusKrwqjCqsKowrM%3D

Error: Command failed with exit code 1: npm run e2e:tests:smoke
    at makeError (/home/runner/work/marketplace-frontend/marketplace-frontend/node_modules/start-server-and-test/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/runner/work/marketplace-frontend/marketplace-frontend/node_modules/start-server-and-test/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command failed with exit code 1: npm run e2e:tests:smoke',
  command: 'npm run e2e:tests:smoke',
  escapedCommand: '"npm run e2e:tests:smoke"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: ***,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Process completed with exit code 1.

**Comment by agoldis** [comment]
Thanks for reporting that issue. That's unfortunate, but understandable. Let us analyze the situation and see what we can do.

**Comment by CaiqueCoelho** [comment]
In my case I downgraded Cypress to version 12.7.4, it was the only way I found that allowed me to continue using cypress-debugger

**Comment by richardszanyi** [comment]
Greetings

We have the following error: 

![image](https://github.com/user-attachments/assets/bb41189f-341d-4fde-8031-03d0152e8dc7)

Any chance for resolution? (I suppose just changing package name might suffice.)

**Comment by agoldis** [comment]
https://docs.currents.dev/getting-started/cypress/integrating-with-cypress/alternative-cypress-binaries

**Comment by ThomasTrepanier** [comment]
Hi! Does anyone know if purchasing the [Cypress Gateway Connector](https://go.cypress.io/continue-recording-with-gateway-connector) will make this plugin work, or does it only enable `cypress-cloud` to allow you to record your runs in a self-hosted service?
Asking as we would like to use `sorry-cypress` for our Dashboard, but we would like to be able to use `cypress-debugger` too.

**Comment by agoldis** [comment]
> Hi! Does anyone know if purchasing the [Cypress Gateway Connector](https://go.cypress.io/continue-recording-with-gateway-connector) will make this plugin work, or does it only enable `cypress-cloud` to allow you to record your runs in a self-hosted service? Asking as we would like to use `sorry-cypress` for our Dashboard, but we would like to be able to use `cypress-debugger` too.

Cypress.io will still be blocking `cypress-debugger` even if you purchase their gateway connector. The only way to use `cypress-debugger` is by using one of [alternative cypress binaries](https://docs.currents.dev/getting-started/cypress/integrating-with-cypress/alternative-cypress-binaries)

**Comment by ThomasTrepanier** [comment]
> Cypress.io will still be blocking `cypress-debugger` even if you purchase their gateway connector. The only way to use `cypress-debugger` is by using one of [alternative cypress binaries](https://docs.currents.dev/getting-started/cypress/integrating-with-cypress/alternative-cypress-binaries)

Thank you for your prompt reply. Using the alternative binaries is however not an option we would like to go with, as we have been using Cypress 13 for a couple months now. I think this information is important for people to know, maybe it would be good to have it in the `Readme` or somewhere more discoverable?

**Comment by agoldis** [comment]
> > Cypress.io will still be blocking `cypress-debugger` even if you purchase their gateway connector. The only way to use `cypress-debugger` is by using one of [alternative cypress binaries](https://docs.currents.dev/getting-started/cypress/integrating-with-cypress/alternative-cypress-binaries)
> 
> Thank you for your prompt reply. Using the alternative binaries is however not an option we would like to go with, as we have been using Cypress 13 for a couple months now. I think this information is important for people to know, maybe it would be good to have it in the `Readme` or somewhere more discoverable?

![currents-2024-08-14-12 06 03@2x](https://github.com/user-attachments/assets/0ab81bd4-3423-4bc2-a8db-bbc25f8187ca)
