### ISSUE TITLE
cypress debugger(https://cypress-debugger.dev/) is down

### ISSUE THREAD

**Issue by rmahnovetsky** [currents-dev/cypress-debugger#78]
### Before opening, please confirm:

- [X] I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-debugger/issues) and [discussions](https://github.com/currents-dev/cypress-debugger/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

https://cypress-debugger.dev/ 

### Describe the bug

https://cypress-debugger.dev/  bucket does not exist

### Expected behavior

https://cypress-debugger.dev/ will work.

### Command and Setup

https://cypress-debugger.dev/ 

### Full log and debug output

404 Not Found
Code: NoSuchBucket
Message: The specified bucket does not exist
BucketName: cypress.app
RequestId: KA4067FXW5RGXA01
HostId: ioGvY1e18b61TIGXGPWe3BIrST/+D/FiLjZ7vV3Omj1PZjQLqC7WveQS7kArzU/uYC8BOVqSYDE=

**Comment by parkuman** [comment]
I have raised this directly with `currents.dev` support. Will report back.

**Comment by agoldis** [comment]
Apologies, fixed now

**Comment by parkuman** [comment]
Thank you!
